### ISSUE TITLE
Update for 5.15 pro and 6 beta?

### ISSUE THREAD

**Issue by louanfontenele** [hung1001/font-awesome-pro#44]
hello, thanks for your repository, there is any update for 5.15 pro and 6 beta?

**Comment by hung1001** [comment]
@louanfontenele  yes, v5 is up to date, and i will update when v6 release

**Comment by louanfontenele** [comment]
thank you!

**Comment by hunghv-1854** [comment]
@louanfontenele v6 here >> [https://fa-v6.hung1001.com/](https://fa-v6.hung1001.com/)

**Comment by hung1001** [comment]
@louanfontenele v6 here: [https://fa-v6.hung1001.com/](https://fa-v6.hung1001.com/)

**Comment by louanfontenele** [comment]
> @louanfontenele v6 here: https://fa-v6.hung1001.com/

thank you so much
